const MN={Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Sept:9,Oct:10,Nov:11,Dec:12,January:1,February:2,March:3,April:4,June:6,July:7,August:8,September:9,October:10,November:11,December:12},WDN={Monday:"周一",Tuesday:"周二",Wednesday:"周三",Thursday:"周四",Friday:"周五",Saturday:"周六",Sunday:"周日",Mon:"周一",Tue:"周二",Wed:"周三",Thu:"周四",Fri:"周五",Sat:"周六",Sun:"周日",today:"今天",Today:"今天",tomorrow:"明天",Tomorrow:"明天",yesterday:"昨天",Yesterday:"昨天"};
const BK={"The Little Prince":"小王子","Animal Farm":"动物庄园","The Great Gatsby":"了不起的盖茨比","Harry Potter and the Philosopher's Stone":"哈利·波特与魔法石","The Hobbit":"霍比特人","Pride and Prejudice":"傲慢与偏见","Dune":"沙丘","Moby-Dick":"白鲸","The Lord of the Rings":"指环王","War and Peace":"战争与和平"};
const DT=s=>BK[s]?BK[s]:!s||!/[A-Za-z]/.test(s)?s:s.replace(/\b(January|February|March|April|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sept|Sep|Oct|Nov|Dec)\.? (\d{1,2})(?:st|nd|rd|th)?(?:,? (\d{4}))?\b/g,(m,a,d,y)=>(y?y+"年":"")+MN[a]+"月"+d+"日").replace(/\b(\d{1,2})(?::(\d{2}))?\s?([AaPp])\.?[Mm]\.?(?![A-Za-z])/g,(m,h,mi,p)=>String(h%12+(/[Pp]/.test(p)?12:0)).padStart(2,"0")+":"+(mi||"00")).replace(/\b(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|Mon|Tue|Wed|Thu|Fri|Sat|Sun|[Tt]oday|[Tt]omorrow|[Yy]esterday)\b/g,m=>WDN[m]).replace(/(\d+)\s?hrs?\b/g,"$1 小时").replace(/(\d+)\s?mins?\b/g,"$1 分钟").replace(/(\d+)\s?secs?\b/g,"$1 秒").replace(/ at /g," ").replace(/日,? /g,"日 ").replace(/(\d{2}:\d{2}(?: GMT[+-]\d{1,2}(?::\d{2})?)?),? ((?:\d{4}年)?\d{1,2}月\d{1,2}日)/g,"$2 $1");
const MSS=globalThis.__claudeZhMissing||(globalThis.__claudeZhMissing=new Set());const MS=n=>{try{if(/^[A-Z][\w .'’-]+, [A-Z][\w .'’-]+, [A-Z]{2}$/.test(n)||/^(?:You said|Claude responded|Show message actions for|More options for)\b/.test(n))return;if(MSS.size<3000&&n&&n.length>=3&&n.length<=300&&/[a-z]{2}/i.test(n)&&!/[一-鿿぀-ヿ가-힯]/.test(n)&&!/https?:|www\.|[\\/]\w+[\\/]|[{}<>=_`|@#]|\.(?:js|ts|py|json|md|exe|dll|png|jpg|txt)\b/i.test(n)&&(/\s/.test(n)?/[a-z]{3}/.test(n):/^[A-Z][a-z]{2,}$/.test(n)))MSS.add(n.trim())}catch{}};
const VI=new Map();for(const [s,t,k,l,f,o] of V){try{let a=VI.get(k);if(!a)VI.set(k,a=[]);a.push([new RegExp(s,f||""),t,l,o])}catch{}}
const SW2=/^(?:of|and|the|for|to|in|on|a|an|by|with|at|&|-|–|·)$/;const LC=c=>!c||/^[$€£¥]?[\d.,]+\s?[kKMBT]?%?$/.test(c)||/[^\x00-\x7f]/.test(c)||(/\s/.test(c)?/^[A-Z0-9]/.test(c)&&c.split(/\s+/).every(w=>/^[A-Z0-9"'“(]/.test(w)||SW2.test(w)):/[A-Z0-9._\-\/@:]/.test(c));
const VC=new Map();
let LM;const ML=n=>{if(!LM){LM=new Map();for(const k in M){const l=k.toLowerCase();if(!LM.has(l))LM.set(l,M[k])}}return LM.get(n.toLowerCase())};
const KR=[["사업자등록번호","营业执照号"],["(미국 델라웨어)","（美国特拉华州）"],["미국 델라웨어","美国特拉华州"],["다리오 아모데이","代表人 Dario Amodei"],["통신판매업 신고","通信销售业申报"],["사업자정보확인","营业者信息查询"],["호스팅제공자","托管服务商"],["대표전화","客服电话"],["주소","地址"],["공정","公正"]];
const KP=n=>{let r=n;for(const [a,b] of KR)r=r.split(a).join(b);r=r.replace(/(\d)호/g,"$1号");return r!==n&&!/[가-힯]/.test(r)?r:void 0};
const VP=n=>{if(n&&n.includes("$2年"))return n.replace(/\$2年/g,"");if(n&&/[가-힯]/.test(n))return n.length<=300?KP(n):void 0;if(!n||n.length>2000||!/[A-Za-z]/.test(n))return;if(VC.has(n))return VC.get(n);let best,bl=-1;const seen=new Set();for(const w of ["*"].concat(n.toLowerCase().split(/[^a-z']+/))){if(w!=="*"&&w.length<3||seen.has(w))continue;seen.add(w);const a=VI.get(w);if(a)for(const [r,t,l,o] of a){if(l<=bl)continue;const m=n.match(r);if(m&&o&&!m.slice(1).every(LC))continue;if(m){best=t.replace(/\$(\d)/g,(_,i)=>{const c=m[i]||"";const z=/\s/.test(c)&&c.length<=40&&(M[c]||ML(c)||(c!==n&&/[A-Za-z]/.test(c)?VP(c):void 0));if(!z&&/\s/.test(c)&&c.length<=40&&/[a-z]{3}/.test(c)&&DT(c)===c)MS(c);return z||DT(c)});bl=l}}}
if(best===void 0&&/\s/.test(n)&&n.length<=80)best=ML(n);
if(best===void 0&&/, | · /.test(n)){const lead=/^(?:,|·) /.test(n)?(n[0]===","?"，":" · "):"",body=lead?n.slice(2):n,sep=body.includes(" · ")||lead===" · "?" · ":"，",ps=body.split(/ · |, (?:and )?/),cap=s=>s.charAt(0).toUpperCase()+s.slice(1),tr=[];for(const p of ps){const c=cap(p.trim()),t=M[p]||M[c]||(p!==n&&c!==n?VP(c):void 0);if(!t){tr.length=0;break}tr.push(t)}if(tr.length===ps.length&&(tr.length>1||lead&&tr.length))best=lead+tr.join(sep)}
// 只差句末标点（如网页版显示 "Memory updated." 而词典里是 "Memory updated"）：去掉标点再查，查到后补上中文标点
if(best===void 0&&n.length<=200&&/[^.!?][.!?]$/.test(n)&&!/[.!?] +[A-Z]/.test(n)){const b=n.slice(0,-1),t=M[b]||VP(b);if(t&&t!==b)best=/[。！？.!?]$/.test(t)?t:t+{".":"。","!":"！","?":"？"}[n.slice(-1)]}
// 代码把几句已翻译的话用空格拼成一段（如限额卡片 "Turn on usage credits…limit. Your weekly limit resets at 2:00 PM."）：按句号拆开，每句都能翻译才拼回
// 从左往右优先取最长的连续几句整体翻译（词典里可能存的是其中两句合起来的整句）（各段结果有缓存，不会重复计算）
if(best===void 0&&n.length<=400&&/[.!?] +[A-Z]/.test(n)){const ps=n.split(/(?<=[.!?]) +(?=[A-Z])/),tr=[];let i=0;while(i<ps.length){let ok=0;for(let j=ps.length;j>i;j--){const seg=ps.slice(i,j).join(" ");if(seg===n)continue;const t=M[seg]||VP(seg);if(t&&t!==seg){tr.push(t);i=j;ok=1;break}}if(!ok){tr.length=0;break}}if(tr.length)best=tr.join("")}
if(VC.size>5000)VC.clear();VC.set(n,best);return best};
const SW=[[/^(Pay|支付)$/,/^(now|现在)$/,"立即支付 "]];const SF=()=>{try{document.querySelectorAll("b").forEach(b=>{const p=b.previousSibling,q=b.nextSibling;if(!p||!q||p.nodeType!==3||q.nodeType!==3)return;const a=p.nodeValue.trim(),c=q.nodeValue.trim();for(const [x,y,t] of SW)if(x.test(a)&&y.test(c)){p.nodeValue=t;q.nodeValue=""}});ZPF();ZSR();ZRT();ZSEG()}catch{}};
// 分段按钮（如自动化任务日程 One-time/Manual/Hourly…）紧挨着排列，父元素文字拼成 "One-timeManual…" 像斜杠命令名，被作者的命令保护跳过。
// 只处理带 aria-pressed 的按钮：按钮里只有一段文字、首字母大写、词典里有整句译文才替换；受保护区域不处理
const ZSEG=()=>{document.querySelectorAll("button[aria-pressed]").forEach(b=>{if(b.childNodes.length!==1||b.firstChild.nodeType!==3||b.closest("[contenteditable],"+C)||Q(b))return;const v=b.firstChild.nodeValue.trim();if(!/^[A-Z][A-Za-z -]{1,30}$/.test(v))return;const t=M[v];if(typeof t==="string"&&t!==v)b.firstChild.nodeValue=t})};
// 用量/额度小横幅里的"重置时间"常被拆成几段（"at" 一段、"Resets/重置" 一段、时间一段），逐段翻译后拼成 "at 重置14:00" 这类。
// 只要一个元素里同时含"重置或 Resets"和时间、没有链接/按钮、整段能翻译，就把所有文字合到第一段、其余清空，不动结构。
const ZRTt=/(\d{1,2}:\d{2}|\d{1,2}\s?[AP]M|\d{1,2}\s?点)/,ZRTk=/重置|Resets|Expires|到期|limit|限额/i;
const ZRT=()=>{document.querySelectorAll("span,div,p").forEach(e=>{if(e.children.length>6||e.closest("[contenteditable],a,button,[role=button],"+C)||Q(e))return;const full=e.textContent.replace(/\s+/g," ").trim();if(!full||full.length>80||e.__zhRT===full||!ZRTt.test(full)||!ZRTk.test(full)||!/[A-Za-z]/.test(full))return;if(e.querySelector("a,button,input,[role=button],[contenteditable]"))return;const w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT),ts=[];let n;while(n=w.nextNode())if(n.nodeValue.trim())ts.push(n);if(!ts.length)return;const t=R(full);if(!t||t===full||!/重置|到期|限额/.test(t))return;ts[0].nodeValue=t;for(let i=1;i<ts.length;i++)ts[i].nodeValue="";e.__zhRT=e.textContent})};
// 被高亮/加粗等纯装饰标签（以及对话框里的代码词，如更新日志里的 `LocalAppData`）拆开的句子（如设置搜索结果 "What should <高亮>Claude</高亮> call you?"）：合起来能整句翻译时，
// 译文放进第一段文字、其余清空。只改文字内容，不动元素结构；含链接/按钮/输入框的不处理，受保护区域不处理
const ZDEC=/^(SPAN|MARK|B|STRONG|EM|I|SMALL|U|CODE|KBD)$/;const ZSR=()=>{document.querySelectorAll("mark,span.text-accent,span.font-semibold,[data-highlight],b,strong,em,[role=dialog] code,[role=dialog] kbd").forEach(h=>{const e=h.parentElement;if(!e||e.__zhSR===e.textContent||e.closest("[contenteditable],a,"+C)||Q(e))return;const kids=[...e.childNodes];if(kids.length<2||kids.length>15)return;const texts=[];for(const k of kids){if(k.nodeType===3){texts.push(k);continue}if(k.nodeType!==1||!ZDEC.test(k.tagName)||k.children.length||k.hasAttribute("onclick"))return;if(k.firstChild&&k.firstChild.nodeType===3)texts.push(k.firstChild)}if(!texts.length||!texts.some(k=>/[A-Za-z]/.test(k.nodeValue)))return;const full=e.textContent.replace(/\s+/g," ").trim();if(full.length>1000||!/[A-Za-z]{3}/.test(full))return;const t=R(full);if(!t||t===full)return;const CK=n=>/^(CODE|KBD)$/.test(n.parentNode.tagName),tg=texts.find(k=>!CK(k))||texts[0];for(const k of texts){if(k===tg)continue;k.nodeValue="";if(CK(k))k.parentNode.style.display="none"}tg.nodeValue=t;e.__zhSR=e.textContent})};
// 设置搜索框的中文助手：搜索在后台按英文比对，输入汉字时在下方列出对应的英文关键词，点击后才填入（平时输入不受影响）
let ZSB,ZSI;const ZSV=typeof HTMLInputElement!=="undefined"?Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value"):null;const ZSHide=()=>{if(ZSB)ZSB.style.display="none"};const ZSH=inp=>{const q=(inp.value||"").trim();if(!/[一-鿿]/.test(q)){ZSHide();return}const hits=[];for(const en in M){const zh=M[en];if(typeof zh!=="string"||en.length>32||!/^[A-Z][A-Za-z0-9 '’&-]*$/.test(en)||!zh.includes(q))continue;hits.push([zh===q?0:zh.startsWith(q)?1:2,en.length,en,zh])}hits.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const seen=new Set(),list=[];for(const h of hits){const k=h[2].toLowerCase();if(seen.has(k))continue;seen.add(k);list.push(h);if(list.length>=6)break}if(!list.length){ZSHide();return}if(!ZSB||!ZSB.isConnected){ZSB=document.createElement("div");ZSB.id="claude-zh-search-helper";ZSB.style.cssText="position:fixed;z-index:2147483647;background:var(--cds-surface-1,#262624);border:1px solid rgba(127,127,127,.35);border-radius:8px;padding:6px;box-shadow:0 6px 24px rgba(0,0,0,.35);font-size:12px;max-width:320px";document.body.appendChild(ZSB)}ZSB.textContent="";const tip=document.createElement("div");tip.textContent="设置搜索只认英文，点击下面的关键词搜索：";tip.style.cssText="opacity:.7;padding:2px 4px 6px";ZSB.appendChild(tip);for(const [, ,en,zh] of list){const b=document.createElement("button");b.type="button";b.textContent=en+"（"+zh+"）";b.style.cssText="display:block;width:100%;text-align:left;padding:4px 6px;border-radius:6px;background:transparent;color:inherit;border:0;cursor:pointer";b.onmouseenter=()=>b.style.background="rgba(127,127,127,.18)";b.onmouseleave=()=>b.style.background="transparent";b.onmousedown=ev=>ev.preventDefault();b.onclick=()=>{ZSV.set.call(inp,en);inp.dispatchEvent(new Event("input",{bubbles:true}));ZSHide();inp.focus()};ZSB.appendChild(b)}const r=inp.getBoundingClientRect();ZSB.style.left=Math.max(4,r.left)+"px";ZSB.style.top=r.bottom+6+"px";ZSB.style.display="block"};try{document.addEventListener("input",ev=>{const t=ev.target;if(!(t instanceof HTMLInputElement))return;const a=t.getAttribute("aria-label")||"";if(!/^(搜索设置|Search settings)$/.test(a))return;ZSI=t;clearTimeout(window.__claudeZhSH);window.__claudeZhSH=setTimeout(()=>ZSH(t),120)},true);document.addEventListener("focusout",ev=>{if(ev.target===ZSI)setTimeout(ZSHide,150)},true)}catch{}
// 富文本编辑器（ProseMirror 等）的提示文字放在 data-placeholder 属性里、用 ::before 显示；编辑器会把外部改动的属性改回去，
// 所以不改元素本身，而是追加一条样式规则：带这个英文提示的元素，::before 直接显示中文
const ZPH=new Set();let ZPS;const ZPF=()=>{document.querySelectorAll("[data-placeholder]").forEach(e=>{const v=e.getAttribute("data-placeholder");if(!v||ZPH.has(v)||!/[A-Za-z]/.test(v))return;const t=R(v);if(!t||t===v)return;let c="";try{c=getComputedStyle(e,"::before").content||""}catch{}if(!c.includes(v)&&!/attr\(\s*data-placeholder/.test(c))return;ZPH.add(v);if(!ZPS||!ZPS.isConnected){ZPS=document.createElement("style");ZPS.id="claude-zh-placeholder";(document.head||document.documentElement).appendChild(ZPS)}ZPS.textContent+="[data-placeholder="+JSON.stringify(v)+"]::before{content:"+JSON.stringify(t)+" !important}\n"})};try{let ZSRq=0;new MutationObserver(()=>{if(!ZSRq){ZSRq=1;requestAnimationFrame(()=>{ZSRq=0;try{ZSR()}catch{}})}clearTimeout(window.__claudeZhSF);window.__claudeZhSF=setTimeout(SF,60)}).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:["data-placeholder"]})}catch{}
