const MN={Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Sept:9,Oct:10,Nov:11,Dec:12,January:1,February:2,March:3,April:4,June:6,July:7,August:8,September:9,October:10,November:11,December:12},WDN={Monday:"周一",Tuesday:"周二",Wednesday:"周三",Thursday:"周四",Friday:"周五",Saturday:"周六",Sunday:"周日",Mon:"周一",Tue:"周二",Wed:"周三",Thu:"周四",Fri:"周五",Sat:"周六",Sun:"周日",today:"今天",Today:"今天",tomorrow:"明天",Tomorrow:"明天",yesterday:"昨天",Yesterday:"昨天"};
const BK={"The Little Prince":"小王子","Animal Farm":"动物庄园","The Great Gatsby":"了不起的盖茨比","Harry Potter and the Philosopher's Stone":"哈利·波特与魔法石","The Hobbit":"霍比特人","Pride and Prejudice":"傲慢与偏见","Dune":"沙丘","Moby-Dick":"白鲸","The Lord of the Rings":"指环王","War and Peace":"战争与和平"};
const DT=s=>BK[s]?BK[s]:!s||!/[A-Za-z]/.test(s)?s:s.replace(/\b(January|February|March|April|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sept|Sep|Oct|Nov|Dec)\.? (\d{1,2})(?:st|nd|rd|th)?(?:,? (\d{4}))?\b/g,(m,a,d,y)=>(y?y+"年":"")+MN[a]+"月"+d+"日").replace(/\b(\d{1,2}(?::\d{2})?)\s?([AaPp])\.?[Mm]\.?(?![A-Za-z])/g,(m,t,p)=>(/[Aa]/.test(p)?"上午 ":"下午 ")+t+(t.includes(":")?"":" 点")).replace(/\b(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|Mon|Tue|Wed|Thu|Fri|Sat|Sun|[Tt]oday|[Tt]omorrow|[Yy]esterday)\b/g,m=>WDN[m]).replace(/(\d+)\s?hrs?\b/g,"$1 小时").replace(/(\d+)\s?mins?\b/g,"$1 分钟").replace(/(\d+)\s?secs?\b/g,"$1 秒").replace(/ at /g," ").replace(/日,? /g,"日 ");
const VI=new Map();for(const [s,t,k,l,f] of V){try{let a=VI.get(k);if(!a)VI.set(k,a=[]);a.push([new RegExp(s,f||""),t,l])}catch{}}
const VC=new Map();
let LM;const ML=n=>{if(!LM){LM=new Map();for(const k in M){const l=k.toLowerCase();if(!LM.has(l))LM.set(l,M[k])}}return LM.get(n.toLowerCase())};
const KR=[["사업자등록번호","营业执照号"],["(미국 델라웨어)","（美国特拉华州）"],["미국 델라웨어","美国特拉华州"],["다리오 아모데이","代表人 Dario Amodei"],["통신판매업 신고","通信销售业申报"],["사업자정보확인","营业者信息查询"],["호스팅제공자","托管服务商"],["대표전화","客服电话"],["주소","地址"],["공정","公正"]];
const KP=n=>{let r=n;for(const [a,b] of KR)r=r.split(a).join(b);r=r.replace(/(\d)호/g,"$1号");return r!==n&&!/[가-힯]/.test(r)?r:void 0};
const VP=n=>{if(n&&n.includes("$2年"))return n.replace(/\$2年/g,"");if(n&&/[가-힯]/.test(n))return n.length<=300?KP(n):void 0;if(!n||n.length>2000||!/[A-Za-z]/.test(n))return;if(VC.has(n))return VC.get(n);let best,bl=-1;const seen=new Set();for(const w of ["*"].concat(n.toLowerCase().split(/[^a-z']+/))){if(w!=="*"&&w.length<3||seen.has(w))continue;seen.add(w);const a=VI.get(w);if(a)for(const [r,t,l] of a){if(l<=bl)continue;const m=n.match(r);if(m){best=t.replace(/\$(\d)/g,(_,i)=>{const c=m[i]||"";return /\s/.test(c)&&c.length<=40&&(M[c]||ML(c)||(c!==n&&/[A-Za-z]/.test(c)?VP(c):void 0))||DT(c)});bl=l}}}
if(best===void 0&&/\s/.test(n)&&n.length<=80)best=ML(n);
if(best===void 0&&/, | · /.test(n)){const lead=/^(?:,|·) /.test(n)?(n[0]===","?"，":" · "):"",body=lead?n.slice(2):n,sep=body.includes(" · ")||lead===" · "?" · ":"，",ps=body.split(/ · |, (?:and )?/),cap=s=>s.charAt(0).toUpperCase()+s.slice(1),tr=[];for(const p of ps){const c=cap(p.trim()),t=M[p]||M[c]||(p!==n&&c!==n?VP(c):void 0);if(!t){tr.length=0;break}tr.push(t)}if(tr.length===ps.length&&(tr.length>1||lead&&tr.length))best=lead+tr.join(sep)}
if(VC.size>5000)VC.clear();VC.set(n,best);return best};
